[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
poem = "3.1.11"
tokio = { version = "1", features = ["full"] }
serde = {version = "1.0.219", features = ["derive"]}
store = {path = "../store"}
jsonwebtoken = "9.3.1"
dotenvy = "0.15.7"

